service: python-wallet

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - ssm:GetParameter
      Resource:
        - Fn::Join:
          - ""
          - - "arn:aws:ssm:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":parameter/Binance_API_Key"
            - ":parameter/Binance_Secret_API_Key"


  